/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiDraftRouteImport } from './routes/api.draft'
import { Route as ApiFilesRouteImport } from './routes/api.files'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiNotesRouteImport } from './routes/api.notes'
import { Route as ApiSearchRouteImport } from './routes/api.search'
import { Route as ApiFilesIdRouteImport } from './routes/api.files.$id'
import { Route as ApiNotesIdRouteImport } from './routes/api.notes.$id'
import { Route as ApiNotesIdEmbedRouteImport } from './routes/api.notes.$id.embed'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDraftRoute = ApiDraftRouteImport.update({
  id: '/api/draft',
  path: '/api/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesRoute = ApiNotesRouteImport.update({
  id: '/api/notes',
  path: '/api/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesIdRoute = ApiFilesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiFilesRoute,
} as any)
const ApiNotesIdRoute = ApiNotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiNotesRoute,
} as any)
const ApiNotesIdEmbedRoute = ApiNotesIdEmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => ApiNotesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/notes': typeof ApiNotesRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/api/notes/$id': typeof ApiNotesIdRouteWithChildren
  '/api/notes/$id/embed': typeof ApiNotesIdEmbedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/notes': typeof ApiNotesRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/api/notes/$id': typeof ApiNotesIdRouteWithChildren
  '/api/notes/$id/embed': typeof ApiNotesIdEmbedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/draft': typeof ApiDraftRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/notes': typeof ApiNotesRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/api/notes/$id': typeof ApiNotesIdRouteWithChildren
  '/api/notes/$id/embed': typeof ApiNotesIdEmbedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/draft'
    | '/api/files'
    | '/api/health'
    | '/api/notes'
    | '/api/search'
    | '/api/files/$id'
    | '/api/notes/$id'
    | '/api/notes/$id/embed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/draft'
    | '/api/files'
    | '/api/health'
    | '/api/notes'
    | '/api/search'
    | '/api/files/$id'
    | '/api/notes/$id'
    | '/api/notes/$id/embed'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/draft'
    | '/api/files'
    | '/api/health'
    | '/api/notes'
    | '/api/search'
    | '/api/files/$id'
    | '/api/notes/$id'
    | '/api/notes/$id/embed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDraftRoute: typeof ApiDraftRoute
  ApiFilesRoute: typeof ApiFilesRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiNotesRoute: typeof ApiNotesRouteWithChildren
  ApiSearchRoute: typeof ApiSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/draft': {
      id: '/api/draft'
      path: '/api/draft'
      fullPath: '/api/draft'
      preLoaderRoute: typeof ApiDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes': {
      id: '/api/notes'
      path: '/api/notes'
      fullPath: '/api/notes'
      preLoaderRoute: typeof ApiNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$id': {
      id: '/api/files/$id'
      path: '/$id'
      fullPath: '/api/files/$id'
      preLoaderRoute: typeof ApiFilesIdRouteImport
      parentRoute: typeof ApiFilesRoute
    }
    '/api/notes/$id': {
      id: '/api/notes/$id'
      path: '/$id'
      fullPath: '/api/notes/$id'
      preLoaderRoute: typeof ApiNotesIdRouteImport
      parentRoute: typeof ApiNotesRoute
    }
    '/api/notes/$id/embed': {
      id: '/api/notes/$id/embed'
      path: '/embed'
      fullPath: '/api/notes/$id/embed'
      preLoaderRoute: typeof ApiNotesIdEmbedRouteImport
      parentRoute: typeof ApiNotesIdRoute
    }
  }
}

interface ApiFilesRouteChildren {
  ApiFilesIdRoute: typeof ApiFilesIdRoute
}

const ApiFilesRouteChildren: ApiFilesRouteChildren = {
  ApiFilesIdRoute: ApiFilesIdRoute,
}

const ApiFilesRouteWithChildren = ApiFilesRoute._addFileChildren(
  ApiFilesRouteChildren,
)

interface ApiNotesIdRouteChildren {
  ApiNotesIdEmbedRoute: typeof ApiNotesIdEmbedRoute
}

const ApiNotesIdRouteChildren: ApiNotesIdRouteChildren = {
  ApiNotesIdEmbedRoute: ApiNotesIdEmbedRoute,
}

const ApiNotesIdRouteWithChildren = ApiNotesIdRoute._addFileChildren(
  ApiNotesIdRouteChildren,
)

interface ApiNotesRouteChildren {
  ApiNotesIdRoute: typeof ApiNotesIdRouteWithChildren
}

const ApiNotesRouteChildren: ApiNotesRouteChildren = {
  ApiNotesIdRoute: ApiNotesIdRouteWithChildren,
}

const ApiNotesRouteWithChildren = ApiNotesRoute._addFileChildren(
  ApiNotesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDraftRoute: ApiDraftRoute,
  ApiFilesRoute: ApiFilesRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiNotesRoute: ApiNotesRouteWithChildren,
  ApiSearchRoute: ApiSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
